In [1]:
import numpy as np
import pandas as pd

In [2]:
data_preprocessed=pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

reason_1  reason_2  reason_3  reason_4  Month  Day of the week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   
2         0         0         0         1      7                2   
3         1         0         0         0      7                3   
4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## Create a target

we will take the median in Absenteeism Time in Hours as a cut-off line

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
target=np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [6]:
target

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['excessive absenteeism']=target

In [8]:
data_preprocessed.head()

reason_1  reason_2  reason_3  reason_4  Month  Day of the week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   
2         0         0         0         1      7                2   
3         1         0         0         0      7                3   
4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   excessive absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [9]:
target.sum()/target.shape[0]

0.45571428571428574

so around 46% of the targets are 1 . A balance of 45-65 is almost always sufficient.

In [10]:
data_with_targets=data_preprocessed.drop(['Absenteeism Time in Hours'],axis=1)

## select inputs for regression

In [11]:
data_with_targets.shape

(700, 15)

In [12]:
data_with_targets.iloc[:,:-1]

reason_1  reason_2  reason_3  reason_4  Month  Day of the week  \
0           0         0         0         1      7                1   
1           0         0         0         0      7                1   
2           0         0         0         1      7                2   
3           1         0         0         0      7                3   
4           0         0         0         1      7                3   
..        ...       ...       ...       ...    ...              ...   
695         1         0         0         0      5                2   
696         1         0         0         0      5                2   
697         1         0         0         0      5                3   
698         0         0         0         1      5                3   
699         0         0         0         1      5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 14 columns]

In [13]:
unscaled_input=data_with_targets.iloc[:,:-1]

## Standarize the data

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
absenteeism_scaler=StandardScaler()

In [18]:
absenteeism_scaler.fit(unscaled_input)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [19]:
scaled_inputs=absenteeism_scaler.transform(unscaled_input)
#.transform() does the actual scaling

In [22]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [23]:
scaled_inputs.shape

(700, 14)

## splitting the data into train & test and schuffle

In [24]:
from sklearn.model_selection import train_test_split

In [26]:
train_test_split(scaled_inputs,target)

[array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297],
        ...,
        [-0.57735027, -0.09298136,  3.17979734, ..., -0.44798003,
          2.67996851, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  0.26848661],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927,  0.26848661]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
         -0.91902997, -0.58968976],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -

*array 1: train dataset with inputs
*array 2: test dataset with inputs
*array 3: train dataset with target
*array 4: test dataset with target

In [37]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,target, train_size=0.8, random_state=20)

In [38]:
x_train.shape

(560, 14)

In [39]:
y_train.shape

(560,)

In [35]:
x_test.shape

(140, 14)

In [36]:
y_test.shape

(140,)

## modeling: logistic regression with sklearn

In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### training the model

In [42]:
reg=LogisticRegression()
reg.fit(x_train,y_train)

C:\Users\ReDI\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [46]:
reg.score(x_train,y_train)

0.7839285714285714

### Manually check the accuracy

In [51]:
model_outputs=reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [52]:
model_outputs==y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [53]:
np.sum((model_outputs==y_train))

439

In [55]:
model_outputs.shape[0]

560

In [57]:
accuracy=np.sum((model_outputs==y_train))/model_outputs.shape[0]
accuracy

0.7839285714285714

### finding intercept and coefficients

In [58]:
reg.intercept_

array([-0.21957576])

In [59]:
reg.coef_

array([[ 2.07452213,  0.33466331,  1.56097327,  1.32750188,  0.1878226 ,
        -0.07060017,  0.70649077, -0.03995965, -0.2009517 , -0.00462411,
         0.31937669, -0.13558227,  0.38168134, -0.33338757]])

In [65]:
feature_name=unscaled_input.columns.values
feature_name

array(['reason_1', 'reason_2', 'reason_3', 'reason_4', 'Month',
       'Day of the week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

Unscaled inputs using the standard scalar.The result was stored in scalar inputs. This shows us that SK learn methods are compatible with pandas data frames but whenever we employ some SK learn function everything is transformed to ndarrays!

That happened with the intercept the coefficients and obviously with the inputs.

In [82]:
summary_table=pd.DataFrame(columns=['Feature'],data=feature_name)
summary_table['coefficient']=np.transpose(reg.coef_)
summary_table

Feature  coefficient
0                  reason_1     2.074522
1                  reason_2     0.334663
2                  reason_3     1.560973
3                  reason_4     1.327502
4                     Month     0.187823
5           Day of the week    -0.070600
6    Transportation Expense     0.706491
7          Distance to Work    -0.039960
8                       Age    -0.200952
9   Daily Work Load Average    -0.004624
10          Body Mass Index     0.319377
11                Education    -0.135582
12                 Children     0.381681
13                     Pets    -0.333388

by default, ndarrays are rows not columns! so we must transpose them

In [83]:
summary_table.index=summary_table.index+1
summary_table.loc[0]=['Intercept', reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

Feature  coefficient
0                 Intercept    -0.219576
1                  reason_1     2.074522
2                  reason_2     0.334663
3                  reason_3     1.560973
4                  reason_4     1.327502
5                     Month     0.187823
6           Day of the week    -0.070600
7    Transportation Expense     0.706491
8          Distance to Work    -0.039960
9                       Age    -0.200952
10  Daily Work Load Average    -0.004624
11          Body Mass Index     0.319377
12                Education    -0.135582
13                 Children     0.381681
14                     Pets    -0.333388

interpreting the coefficients

In [85]:
summary_table['odds ratio']=np.exp(summary_table.coefficient)
summary_table

Feature  coefficient  odds ratio
0                 Intercept    -0.219576    0.802859
1                  reason_1     2.074522    7.960741
2                  reason_2     0.334663    1.397470
3                  reason_3     1.560973    4.763455
4                  reason_4     1.327502    3.771610
5                     Month     0.187823    1.206619
6           Day of the week    -0.070600    0.931834
7    Transportation Expense     0.706491    2.026866
8          Distance to Work    -0.039960    0.960828
9                       Age    -0.200952    0.817952
10  Daily Work Load Average    -0.004624    0.995387
11          Body Mass Index     0.319377    1.376270
12                Education    -0.135582    0.873207
13                 Children     0.381681    1.464745
14                     Pets    -0.333388    0.716492

In [88]:
summary_table.sort_values('odds ratio', ascending=False)

Feature  coefficient  odds ratio
1                  reason_1     2.074522    7.960741
3                  reason_3     1.560973    4.763455
4                  reason_4     1.327502    3.771610
7    Transportation Expense     0.706491    2.026866
13                 Children     0.381681    1.464745
2                  reason_2     0.334663    1.397470
11          Body Mass Index     0.319377    1.376270
5                     Month     0.187823    1.206619
10  Daily Work Load Average    -0.004624    0.995387
8          Distance to Work    -0.039960    0.960828
6           Day of the week    -0.070600    0.931834
12                Education    -0.135582    0.873207
9                       Age    -0.200952    0.817952
0                 Intercept    -0.219576    0.802859
14                     Pets    -0.333388    0.716492

Here is a big problem. When we standardized the inputs we also standardized the dummies. This is bad practice because when we standardized we lose the whole interpretability of a dummy. So we should use the CustomScaler from the beginning!