In [1]:
import numpy as np
import pandas as pd

In [2]:
data_preprocessed=pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

reason_1  reason_2  reason_3  reason_4  Month  Day of the week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   
2         0         0         0         1      7                2   
3         1         0         0         0      7                3   
4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## Create a target

we will take the median in Absenteeism Time in Hours as a cut-off line

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
target=np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [6]:
target

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['excessive absenteeism']=target

In [8]:
data_preprocessed.head()

reason_1  reason_2  reason_3  reason_4  Month  Day of the week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   
2         0         0         0         1      7                2   
3         1         0         0         0      7                3   
4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   excessive absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [9]:
target.sum()/target.shape[0]

0.45571428571428574

so around 46% of the targets are 1 . A balance of 45-65 is almost always sufficient.

In [10]:
data_with_targets=data_preprocessed.drop(['Absenteeism Time in Hours','Day of the week','Distance to Work','Daily Work Load Average',],axis=1)

## select inputs for regression

In [11]:
data_with_targets.shape

(700, 12)

In [12]:
data_with_targets.iloc[:,:-1]

reason_1  reason_2  reason_3  reason_4  Month  Transportation Expense  \
0           0         0         0         1      7                     289   
1           0         0         0         0      7                     118   
2           0         0         0         1      7                     179   
3           1         0         0         0      7                     279   
4           0         0         0         1      7                     289   
..        ...       ...       ...       ...    ...                     ...   
695         1         0         0         0      5                     179   
696         1         0         0         0      5                     225   
697         1         0         0         0      5                     330   
698         0         0         0         1      5                     235   
699         0         0         0         1      5                     291   

     Age  Body Mass Index  Education  Children  Pets  
0     33               30          0         2     1  
1     50               31          0         1     0  
2     38               31          0         0     0  
3     39               24          0         2     0  
4     33               30          0         2     1  
..   ...              ...        ...       ...   ...  
695   40               22          1         2     0  
696   28               24          0         1     2  
697   28               25          1         0     0  
698   32               25          1         0     0  
699   40               25          0         1     1  

[700 rows x 11 columns]

In [13]:
unscaled_input=data_with_targets.iloc[:,:-1]

## Standarize the data

In [14]:
#from sklearn.preprocessing import StandardScaler

In [15]:
#absenteeism_scaler.fit(unscaled_input)

In [16]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [17]:
unscaled_input.columns.values

array(['reason_1', 'reason_2', 'reason_3', 'reason_4', 'Month',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [18]:
#columns_to_scale=['Month', 'Day of the week', 'Transportation Expense', 'Distance to Work',
      # 'Age', 'Daily Work Load Average', 'Body Mass Index',
      # 'Children', 'Pets']
        
columns_to_omit=['reason_1', 'reason_2', 'reason_3', 'reason_4','Education']
columns_to_scale=[x for x in unscaled_input.columns.values if x not in columns_to_omit]

In [19]:
absenteeism_scaler=CustomScaler(columns_to_scale)

In [20]:
absenteeism_scaler.fit(unscaled_input)

CustomScaler(columns=['Month', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [21]:
scaled_inputs=absenteeism_scaler.transform(unscaled_input)
#.transform() does the actual scaling

In [22]:
scaled_inputs

reason_1  reason_2  reason_3  reason_4     Month  Transportation Expense  \
0           0         0         0         1  0.182726                1.005844   
1           0         0         0         0  0.182726               -1.574681   
2           0         0         0         1  0.182726               -0.654143   
3           1         0         0         0  0.182726                0.854936   
4           0         0         0         1  0.182726                1.005844   
..        ...       ...       ...       ...       ...                     ...   
695         1         0         0         0 -0.388293               -0.654143   
696         1         0         0         0 -0.388293                0.040034   
697         1         0         0         0 -0.388293                1.624567   
698         0         0         0         1 -0.388293                0.190942   
699         0         0         0         1 -0.388293                1.036026   

          Age  Body Mass Index  Education  Children      Pets  
0   -0.536062         0.767431          0  0.880469  0.268487  
1    2.130803         1.002633          0 -0.019280 -0.589690  
2    0.248310         1.002633          0 -0.919030 -0.589690  
3    0.405184        -0.643782          0  0.880469 -0.589690  
4   -0.536062         0.767431          0  0.880469  0.268487  
..        ...              ...        ...       ...       ...  
695  0.562059        -1.114186          1  0.880469 -0.589690  
696 -1.320435        -0.643782          0 -0.019280  1.126663  
697 -1.320435        -0.408580          1 -0.919030 -0.589690  
698 -0.692937        -0.408580          1 -0.919030 -0.589690  
699  0.562059        -0.408580          0 -0.019280  0.268487  

[700 rows x 11 columns]

In [23]:
scaled_inputs.shape

(700, 11)

## splitting the data into train & test and schuffle

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
train_test_split(scaled_inputs,target)

[     reason_1  reason_2  reason_3  reason_4     Month  Transportation Expense  \
 42          0         0         0         1  0.753746               -0.654143   
 598         0         0         0         1 -1.244823               -0.654143   
 645         0         0         0         1 -0.959313               -0.654143   
 609         0         0         0         1 -1.244823                0.190942   
 9           0         0         0         1  0.182726                0.190942   
 ..        ...       ...       ...       ...       ...                     ...   
 235         0         0         0         1 -0.102784                0.040034   
 334         1         0         0         0  1.324766                0.568211   
 543         1         0         0         0  1.324766                0.040034   
 0           0         0         0         1  0.182726                1.005844   
 115         0         0         0         1 -1.530333               -1.574681   
 
           Age

*array 1: train dataset with inputs
*array 2: test dataset with inputs
*array 3: train dataset with target
*array 4: test dataset with target

In [26]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,target, train_size=0.8, random_state=20)

In [27]:
x_train.shape

(560, 11)

In [28]:
y_train.shape

(560,)

In [29]:
x_test.shape

(140, 11)

In [30]:
y_test.shape

(140,)

## modeling: logistic regression with sklearn

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### training the model

In [32]:
reg=LogisticRegression()
reg.fit(x_train,y_train)

C:\Users\ReDI\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [33]:
reg.score(x_train,y_train)

0.775

### Manually check the accuracy

In [34]:
model_outputs=reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [35]:
model_outputs==y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [36]:
np.sum((model_outputs==y_train))

434

In [37]:
model_outputs.shape[0]

560

In [38]:
accuracy=np.sum((model_outputs==y_train))/model_outputs.shape[0]
accuracy

0.775

### finding intercept and coefficients

In [39]:
reg.intercept_

array([-1.46547112])

In [40]:
reg.coef_

array([[ 2.62749942,  0.86338637,  2.96050661,  0.66390745,  0.15493732,
         0.59979822, -0.17245127,  0.27568526, -0.23452541,  0.34249662,
        -0.2775137 ]])

In [41]:
feature_name=unscaled_input.columns.values
feature_name

array(['reason_1', 'reason_2', 'reason_3', 'reason_4', 'Month',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

Unscaled inputs using the standard scalar.The result was stored in scalar inputs. This shows us that SK learn methods are compatible with pandas data frames but whenever we employ some SK learn function everything is transformed to ndarrays!

That happened with the intercept the coefficients and obviously with the inputs.

In [42]:
summary_table=pd.DataFrame(columns=['Feature'],data=feature_name)
summary_table['coefficient']=np.transpose(reg.coef_)
summary_table

Feature  coefficient
0                 reason_1     2.627499
1                 reason_2     0.863386
2                 reason_3     2.960507
3                 reason_4     0.663907
4                    Month     0.154937
5   Transportation Expense     0.599798
6                      Age    -0.172451
7          Body Mass Index     0.275685
8                Education    -0.234525
9                 Children     0.342497
10                    Pets    -0.277514

by default, ndarrays are rows not columns! so we must transpose them

In [43]:
summary_table.index=summary_table.index+1
summary_table.loc[0]=['Intercept', reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

Feature  coefficient
0                Intercept    -1.465471
1                 reason_1     2.627499
2                 reason_2     0.863386
3                 reason_3     2.960507
4                 reason_4     0.663907
5                    Month     0.154937
6   Transportation Expense     0.599798
7                      Age    -0.172451
8          Body Mass Index     0.275685
9                Education    -0.234525
10                Children     0.342497
11                    Pets    -0.277514

interpreting the coefficients

In [44]:
summary_table['odds ratio']=np.exp(summary_table.coefficient)
summary_table

Feature  coefficient  odds ratio
0                Intercept    -1.465471    0.230969
1                 reason_1     2.627499   13.839121
2                 reason_2     0.863386    2.371177
3                 reason_3     2.960507   19.307751
4                 reason_4     0.663907    1.942367
5                    Month     0.154937    1.167585
6   Transportation Expense     0.599798    1.821751
7                      Age    -0.172451    0.841599
8          Body Mass Index     0.275685    1.317433
9                Education    -0.234525    0.790946
10                Children     0.342497    1.408460
11                    Pets    -0.277514    0.757665

In [45]:
summary_table.sort_values('odds ratio', ascending=False)

Feature  coefficient  odds ratio
3                 reason_3     2.960507   19.307751
1                 reason_1     2.627499   13.839121
2                 reason_2     0.863386    2.371177
4                 reason_4     0.663907    1.942367
6   Transportation Expense     0.599798    1.821751
10                Children     0.342497    1.408460
8          Body Mass Index     0.275685    1.317433
5                    Month     0.154937    1.167585
7                      Age    -0.172451    0.841599
9                Education    -0.234525    0.790946
11                    Pets    -0.277514    0.757665
0                Intercept    -1.465471    0.230969

therefore deleting those three variables did not effect our model accuracy :)

## testing the model

In [46]:
reg.score(x_test,y_test)

0.75

In [49]:
predicted_proba=reg.predict_proba(x_test)
predicted_proba

array([[0.71221976, 0.28778024],
       [0.58760009, 0.41239991],
       [0.44337438, 0.55662562],
       [0.77903962, 0.22096038],
       [0.08458343, 0.91541657],
       [0.33103371, 0.66896629],
       [0.29792496, 0.70207504],
       [0.12956221, 0.87043779],
       [0.78307821, 0.21692179],
       [0.74708659, 0.25291341],
       [0.49514969, 0.50485031],
       [0.22640297, 0.77359703],
       [0.07030984, 0.92969016],
       [0.73504052, 0.26495948],
       [0.30533085, 0.69466915],
       [0.55035881, 0.44964119],
       [0.55027426, 0.44972574],
       [0.53930442, 0.46069558],
       [0.40117774, 0.59882226],
       [0.05320682, 0.94679318],
       [0.69874615, 0.30125385],
       [0.77903962, 0.22096038],
       [0.41634563, 0.58365437],
       [0.41634563, 0.58365437],
       [0.2412915 , 0.7587085 ],
       [0.74317087, 0.25682913],
       [0.51065194, 0.48934806],
       [0.85703303, 0.14296697],
       [0.19934235, 0.80065765],
       [0.77903962, 0.22096038],
       [0.

In [50]:
predicted_proba.shape

(140, 2)

The first column: shows the probability our model assigned to the observation being zero and 
the second: the probability the model assigned to the observation being one.

In [51]:
predicted_proba[:,1]

array([0.28778024, 0.41239991, 0.55662562, 0.22096038, 0.91541657,
       0.66896629, 0.70207504, 0.87043779, 0.21692179, 0.25291341,
       0.50485031, 0.77359703, 0.92969016, 0.26495948, 0.69466915,
       0.44964119, 0.44972574, 0.46069558, 0.59882226, 0.94679318,
       0.30125385, 0.22096038, 0.58365437, 0.58365437, 0.7587085 ,
       0.25682913, 0.48934806, 0.14296697, 0.80065765, 0.22096038,
       0.37028423, 0.68316787, 0.68825755, 0.52694241, 0.22096038,
       0.53492642, 0.22453007, 0.74389237, 0.40329273, 0.60301627,
       0.21343976, 0.45483346, 0.2403088 , 0.4388431 , 0.82622935,
       0.57857132, 0.69461059, 0.28778024, 0.22209028, 0.2061074 ,
       0.57577123, 0.36438663, 0.66896629, 0.27128561, 0.83334736,
       0.43399232, 0.88600663, 0.23396355, 0.37170685, 0.38209505,
       0.69796139, 0.65909803, 0.29392197, 0.79686146, 0.20956093,
       0.2699923 , 0.10399887, 0.22453007, 0.73944244, 0.30081832,
       0.22453007, 0.32688766, 0.90337554, 0.45745729, 0.59997

in reality Logistic regression models calculate these probabilities in the background:
if the probability is below 0.5: It places a zero 
otherwise is 1

## Save the model

In [58]:
import pickle

In [59]:
with open('model','wb')as file:
    pickle.dump(reg,file)

In [60]:
with open('scaler','wb')as file:
    pickle.dump(absenteeism_scaler,file)