In [1]:
import numpy as np
import pandas as pd

In [2]:
data_preprocessed=pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

reason_1  reason_2  reason_3  reason_4  Month  Day of the week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   
2         0         0         0         1      7                2   
3         1         0         0         0      7                3   
4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## Create a target

we will take the median in Absenteeism Time in Hours as a cut-off line

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
target=np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [6]:
target

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['excessive absenteeism']=target

In [8]:
data_preprocessed.head()

reason_1  reason_2  reason_3  reason_4  Month  Day of the week  \
0         0         0         0         1      7                1   
1         0         0         0         0      7                1   
2         0         0         0         1      7                2   
3         1         0         0         0      7                3   
4         0         0         0         1      7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   excessive absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [9]:
target.sum()/target.shape[0]

0.45571428571428574

so around 46% of the targets are 1 . A balance of 45-65 is almost always sufficient.

In [10]:
data_with_targets=data_preprocessed.drop(['Absenteeism Time in Hours'],axis=1)

## select inputs for regression

In [11]:
data_with_targets.shape

(700, 15)

In [12]:
data_with_targets.iloc[:,:-1]

reason_1  reason_2  reason_3  reason_4  Month  Day of the week  \
0           0         0         0         1      7                1   
1           0         0         0         0      7                1   
2           0         0         0         1      7                2   
3           1         0         0         0      7                3   
4           0         0         0         1      7                3   
..        ...       ...       ...       ...    ...              ...   
695         1         0         0         0      5                2   
696         1         0         0         0      5                2   
697         1         0         0         0      5                3   
698         0         0         0         1      5                3   
699         0         0         0         1      5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 14 columns]

In [13]:
unscaled_input=data_with_targets.iloc[:,:-1]

## Standarize the data

In [14]:
#from sklearn.preprocessing import StandardScaler

In [15]:
#absenteeism_scaler.fit(unscaled_input)

In [16]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [17]:
unscaled_input.columns.values

array(['reason_1', 'reason_2', 'reason_3', 'reason_4', 'Month',
       'Day of the week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [18]:
columns_to_scale=['Month', 'Day of the week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index',
       'Children', 'Pets']

In [19]:
absenteeism_scaler=CustomScaler(columns_to_scale)

In [20]:
absenteeism_scaler.fit(unscaled_input)

CustomScaler(columns=['Month', 'Day of the week', 'Transportation Expense',
                      'Distance to Work', 'Age', 'Daily Work Load Average',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [21]:
scaled_inputs=absenteeism_scaler.transform(unscaled_input)
#.transform() does the actual scaling

In [22]:
scaled_inputs

reason_1  reason_2  reason_3  reason_4     Month  Day of the week  \
0           0         0         0         1  0.182726        -0.683704   
1           0         0         0         0  0.182726        -0.683704   
2           0         0         0         1  0.182726        -0.007725   
3           1         0         0         0  0.182726         0.668253   
4           0         0         0         1  0.182726         0.668253   
..        ...       ...       ...       ...       ...              ...   
695         1         0         0         0 -0.388293        -0.007725   
696         1         0         0         0 -0.388293        -0.007725   
697         1         0         0         0 -0.388293         0.668253   
698         0         0         0         1 -0.388293         0.668253   
699         0         0         0         1 -0.388293         0.668253   

     Transportation Expense  Distance to Work       Age  \
0                  1.005844          0.412816 -0.536062   
1                 -1.574681         -1.141882  2.130803   
2                 -0.654143          1.426749  0.248310   
3                  0.854936         -1.682647  0.405184   
4                  1.005844          0.412816 -0.536062   
..                      ...               ...       ...   
695               -0.654143         -0.533522  0.562059   
696                0.040034         -0.263140 -1.320435   
697                1.624567         -0.939096 -1.320435   
698                0.190942         -0.939096 -0.692937   
699                1.036026          0.074838  0.562059   

     Daily Work Load Average  Body Mass Index  Education  Children      Pets  
0                  -0.806331         0.767431          0  0.880469  0.268487  
1                  -0.806331         1.002633          0 -0.019280 -0.589690  
2                  -0.806331         1.002633          0 -0.919030 -0.589690  
3                  -0.806331        -0.643782          0  0.880469 -0.589690  
4                  -0.806331         0.767431          0  0.880469  0.268487  
..                       ...              ...        ...       ...       ...  
695                -0.853789        -1.114186          1  0.880469 -0.589690  
696                -0.853789        -0.643782          0 -0.019280  1.126663  
697                -0.853789        -0.408580          1 -0.919030 -0.589690  
698                -0.853789        -0.408580          1 -0.919030 -0.589690  
699                -0.853789        -0.408580          0 -0.019280  0.268487  

[700 rows x 14 columns]

In [23]:
scaled_inputs.shape

(700, 14)

## splitting the data into train & test and schuffle

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
train_test_split(scaled_inputs,target)

[     reason_1  reason_2  reason_3  reason_4     Month  Day of the week  \
 573         0         0         0         1 -1.530333         1.344231   
 274         1         0         0         0  0.753746        -1.359682   
 621         0         0         0         1 -0.959313        -0.683704   
 5           0         0         0         1  0.182726         1.344231   
 238         1         0         0         0  0.182726         1.344231   
 ..        ...       ...       ...       ...       ...              ...   
 302         0         0         0         1  1.039256         2.696187   
 20          1         0         0         0  0.468236        -0.007725   
 524         1         0         0         0  1.039256         0.668253   
 42          0         0         0         1  0.753746        -0.683704   
 327         1         0         0         0  1.324766        -0.007725   
 
      Transportation Expense  Distance to Work       Age  \
 573               -0.654143         -

*array 1: train dataset with inputs
*array 2: test dataset with inputs
*array 3: train dataset with target
*array 4: test dataset with target

In [26]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,target, train_size=0.8, random_state=20)

In [27]:
x_train.shape

(560, 14)

In [28]:
y_train.shape

(560,)

In [29]:
x_test.shape

(140, 14)

In [30]:
y_test.shape

(140,)

## modeling: logistic regression with sklearn

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### training the model

In [32]:
reg=LogisticRegression()
reg.fit(x_train,y_train)

C:\Users\ReDI\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [33]:
reg.score(x_train,y_train)

0.7714285714285715

### Manually check the accuracy

In [34]:
model_outputs=reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [35]:
model_outputs==y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [36]:
np.sum((model_outputs==y_train))

432

In [37]:
model_outputs.shape[0]

560

In [38]:
accuracy=np.sum((model_outputs==y_train))/model_outputs.shape[0]
accuracy

0.7714285714285715

### finding intercept and coefficients

In [39]:
reg.intercept_

array([-1.47082548])

In [40]:
reg.coef_

array([[ 2.62614283,  0.84432   ,  2.93971875,  0.67771914,  0.16145652,
        -0.08257256,  0.60695978, -0.00741802, -0.16862442, -0.00383568,
         0.26749958, -0.23085763,  0.35572764, -0.28559431]])

In [41]:
feature_name=unscaled_input.columns.values
feature_name

array(['reason_1', 'reason_2', 'reason_3', 'reason_4', 'Month',
       'Day of the week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

Unscaled inputs using the standard scalar.The result was stored in scalar inputs. This shows us that SK learn methods are compatible with pandas data frames but whenever we employ some SK learn function everything is transformed to ndarrays!

That happened with the intercept the coefficients and obviously with the inputs.

In [42]:
summary_table=pd.DataFrame(columns=['Feature'],data=feature_name)
summary_table['coefficient']=np.transpose(reg.coef_)
summary_table

Feature  coefficient
0                  reason_1     2.626143
1                  reason_2     0.844320
2                  reason_3     2.939719
3                  reason_4     0.677719
4                     Month     0.161457
5           Day of the week    -0.082573
6    Transportation Expense     0.606960
7          Distance to Work    -0.007418
8                       Age    -0.168624
9   Daily Work Load Average    -0.003836
10          Body Mass Index     0.267500
11                Education    -0.230858
12                 Children     0.355728
13                     Pets    -0.285594

by default, ndarrays are rows not columns! so we must transpose them

In [43]:
summary_table.index=summary_table.index+1
summary_table.loc[0]=['Intercept', reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

Feature  coefficient
0                 Intercept    -1.470825
1                  reason_1     2.626143
2                  reason_2     0.844320
3                  reason_3     2.939719
4                  reason_4     0.677719
5                     Month     0.161457
6           Day of the week    -0.082573
7    Transportation Expense     0.606960
8          Distance to Work    -0.007418
9                       Age    -0.168624
10  Daily Work Load Average    -0.003836
11          Body Mass Index     0.267500
12                Education    -0.230858
13                 Children     0.355728
14                     Pets    -0.285594

interpreting the coefficients

In [44]:
summary_table['odds ratio']=np.exp(summary_table.coefficient)
summary_table

Feature  coefficient  odds ratio
0                 Intercept    -1.470825    0.229736
1                  reason_1     2.626143   13.820360
2                  reason_2     0.844320    2.326395
3                  reason_3     2.939719   18.910527
4                  reason_4     0.677719    1.969381
5                     Month     0.161457    1.175221
6           Day of the week    -0.082573    0.920745
7    Transportation Expense     0.606960    1.834845
8          Distance to Work    -0.007418    0.992609
9                       Age    -0.168624    0.844826
10  Daily Work Load Average    -0.003836    0.996172
11          Body Mass Index     0.267500    1.306693
12                Education    -0.230858    0.793852
13                 Children     0.355728    1.427219
14                     Pets    -0.285594    0.751567

In [45]:
summary_table.sort_values('odds ratio', ascending=False)

Feature  coefficient  odds ratio
3                  reason_3     2.939719   18.910527
1                  reason_1     2.626143   13.820360
2                  reason_2     0.844320    2.326395
4                  reason_4     0.677719    1.969381
7    Transportation Expense     0.606960    1.834845
13                 Children     0.355728    1.427219
11          Body Mass Index     0.267500    1.306693
5                     Month     0.161457    1.175221
10  Daily Work Load Average    -0.003836    0.996172
8          Distance to Work    -0.007418    0.992609
6           Day of the week    -0.082573    0.920745
9                       Age    -0.168624    0.844826
12                Education    -0.230858    0.793852
14                     Pets    -0.285594    0.751567
0                 Intercept    -1.470825    0.229736

reason zero or no reason which is the baseline of the model.
We also notice that daily work load, average distance to work and day of the week seemed to have the lowest impact. so lets try dropping them in the next version!